# Site settings
title:        MolView
author:       Herman Bergwerf
description:  MolView is an intuitive, Open-Source web-application to make chemistry and biology more awesome!
url:          blog.molview.org

# Optional features
animated:            false
show_related_posts:  false

# Disqus post comments
# (leave blank to disable Disqus)
# disqus_shortname: "molview"

# Social icons
show_social_icons:  true
github_username:    molview

# Build settings
markdown:      kramdown
redcarpet:
  extensions:  [smart, tables, with_toc_data]
permalink:     pretty
paginate:      3
sass:
  compressed:  true
plugins:       [jekyll-paginate]
